spring:
  application:
    name: MySix
  profiles:
    active: ${ENV:web}
server:
  port: 8888


#logging:
#  file:
#    path: E:/log
#  config: classpath:logback-spring.xml

timeTask:
  t1: 0 0/20 * * * ?