mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件所在路径
  type-aliases-package: com.cn.mysix.bean  #对应实体类路径



#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: root
#    password: root
#    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
spring:
  boot:
    admin:
      client:
        url: 'http://localhost:8888'
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always